sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t seth/image -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true seth/image npm test -- --coverage

after_success:
  - docker build -t sethodessa/multi-client ./client
  - docker build -t sethodessa/multi-nginx ./nginx
  - docker build -t sethodessa/multi-server ./server
  - docker build -t sethodessa/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sethodessa/multi-docker:multi-client
  - docker push sethodessa/multi-docker:multi-nginx
  - docker push sethodessa/multi-docker:multi-server
  - docker push sethodessa/multi-docker:multi-worker
